// backend/routes/products.routes.js
const express = require('express');
const router = express.Router();
const db = require('../config/db'); // Your database connection
const authMiddleware = require('../middleware/auth.middleware'); // [cite: uploaded:auth.middleware.js]
const authorizeRoles = require('../middleware/role.middleware'); // [cite: uploaded:role.middleware.js]

// Add a new product - PROTECTED (ADMIN only)
router.post('/add', authMiddleware, authorizeRoles('admin'), async (req, res) => { // Changed from /create to /add for consistency
  try {
    const {
      id, // Assuming ID can be provided or will be auto-generated by DB
      name,
      category,
      subcategory,
      buying_price,
      selling_price,
      quantity,
      threshold,
      expiry,
      supplier,
      contact,
      status // This status is for product stock status (in_stock, low_stock, out_of_stock)
    } = req.body;

    // Basic validation
    if (!name || !category || buying_price == null || selling_price == null || quantity == null || threshold == null) {
      return res.status(400).json({ message: 'Required fields (name, category, prices, quantity, threshold) are missing' });
    }

    // Optional: Check if product ID already exists if it's not auto-increment
    if (id) {
        const [existingProduct] = await db.execute('SELECT id FROM products WHERE id = ?', [id]);
        if (existingProduct.length > 0) {
            return res.status(409).json({ message: 'Product with this ID already exists.' });
        }
    }


    const [result] = await db.execute(
      `INSERT INTO products (
        ${id ? 'id, ' : ''}name, category, subcategory, buying_price, selling_price, quantity,
        threshold, expiry, supplier, contact, status, action
      ) VALUES (${id ? '?, ' : ''}?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        ...(id ? [id] : []), // Include ID if provided
        name,
        category,
        subcategory || null,
        buying_price,
        selling_price,
        quantity,
        threshold,
        expiry || null, // Ensure expiry is in YYYY-MM-DD format if date type in DB
        supplier || null,
        contact || null,
        status || 'in_stock', // Default status
        'active' // Default action
      ]
    );

    res.status(201).json({ message: 'Product added successfully', productId: result.insertId || id }); // Use insertId or provided ID
  } catch (err) {
    console.error('Add Product Error:', err);
    res.status(500).json({ message: 'Failed to add product', error: err.message });
  }
});

// Update existing product - PROTECTED (ADMIN only)
router.put('/:id', authMiddleware, authorizeRoles('admin'), async (req, res) => { // Changed from /edit/:id to /:id for RESTful consistency
  const { id } = req.params;
  const {
    name,
    category,
    subcategory,
    buying_price,
    selling_price,
    quantity,
    threshold,
    expiry,
    supplier,
    contact,
    status
  } = req.body;

  // Basic validation
  if (!name || !category || buying_price == null || selling_price == null || quantity == null || threshold == null) {
    return res.status(400).json({ message: 'Required fields (name, category, prices, quantity, threshold) are missing' });
  }

  try {
    const [result] = await db.execute(
      `UPDATE products SET
        name = ?, category = ?, subcategory = ?, buying_price = ?, selling_price = ?,
        quantity = ?, threshold = ?, expiry = ?, supplier = ?, contact = ?, status = ?
        WHERE id = ? AND action = 'active'`, // Only update active products
      [
        name,
        category,
        subcategory || null,
        buying_price,
        selling_price,
        quantity,
        threshold,
        expiry || null, // Ensure expiry is in YYYY-MM-DD format if date type in DB
        supplier || null,
        contact || null,
        status || 'in_stock',
        id
      ]
    );

    if (result.affectedRows === 0) {
        return res.status(404).json({ message: 'Product not found or not active.' });
    }

    res.status(200).json({ message: 'Product updated successfully' });
  } catch (err) {
    console.error('Update Product Error:', err);
    res.status(500).json({ message: 'Failed to update product', error: err.message });
  }
});

// Soft delete (set action to inactive) - PROTECTED (ADMIN only)
router.delete('/:id', authMiddleware, authorizeRoles('admin'), async (req, res) => { // Changed from /delete/:id to /:id for RESTful consistency
  const { id } = req.params;

  try {
    const [result] = await db.execute(`UPDATE products SET action = 'inactive' WHERE id = ?`, [id]);

    if (result.affectedRows === 0) {
        return res.status(404).json({ message: 'Product not found or already inactive.' });
    }

    res.status(200).json({ message: 'Product deactivated successfully' }); // Changed message to reflect soft delete
  } catch (err) {
    console.error('Soft Delete Product Error:', err);
    res.status(500).json({ message: 'Failed to deactivate product', error: err.message });
  }
});

// Get all products (active and inactive) for Admin management - PROTECTED (ADMIN only)
router.get('/all', authMiddleware, authorizeRoles('admin'), async (req, res) => { // New endpoint for all products
  try {
    const [rows] = await db.execute(`SELECT * FROM products ORDER BY name ASC`);
    res.status(200).json(rows);
  } catch (err) {
    console.error('Fetch All Products Error:', err);
    res.status(500).json({ message: 'Failed to fetch all products', error: err.message });
  }
});

// Get all active products (for general use, e.g., sales, customer views) - Can be public or protected
router.get('/', async (req, res) => { // Existing endpoint, now only for active products
  try {
    const [rows] = await db.execute(`SELECT * FROM products WHERE action = 'active' ORDER BY name ASC`);
    res.status(200).json(rows);
  } catch (err) {
    console.error('Fetch Active Products Error:', err);
    res.status(500).json({ message: 'Failed to fetch active products', error: err.message });
    }
    });


module.exports = router;